services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      VITE_BASE_URL: "http://localhost:4000"
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/tmp        
      - $HOME/.kube:/root/.kube 
    environment:
      - KUBECONFIG=/root/.kube/config
    user: "root"
    command: ["air"]
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
