name: Add new contributors to readme.md

on:
  workflow_dispatch:

  pull_request:
    types:
      - closed

jobs:
  contrib-readme-job:
    if: github.event.pull_request.merged == true && github.repository_owner == 'kubestellar' # Only run for merged PRs in 'kubestellar'
    runs-on: ubuntu-latest
    name: A job to automate contributors in README
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Contributors List Action
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          image_size: 100
          readme_path: README.md
          use_username: false
          columns_per_row: 6
          collaborators: all  # Avoids permission issue
          commit_message: "docs(contributor): contrib-readme-action has updated readme"
          auto_detect_branch_protection: false  # Avoids branch protection issues
          pr_title_on_protected: "docs(contributor): contributors readme action update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for a few seconds
        run: sleep 5
        
      - name: Fetch All Remote Branches
        run: |
          git fetch --all
          echo "Fetched all remote branches"

      - name: Detect the Branch Created by the Action
        id: get-branch
        run: |
          echo "Available branches:"
          git for-each-ref --sort=-committerdate --format='%(refname:short)' refs/remotes/origin

          CURRENT_BRANCH=$(git for-each-ref --sort=-committerdate --format='%(refname:short)' refs/remotes/origin | grep "contributors-readme-action" | head -n 1)
          CURRENT_BRANCH_CLEAN=${CURRENT_BRANCH#origin/}
          echo "CURRENT_BRANCH=$CURRENT_BRANCH_CLEAN" >> $GITHUB_ENV
          echo "Branch created by action: $CURRENT_BRANCH_CLEAN"

          if [ -z "$CURRENT_BRANCH_CLEAN" ]; then
            echo "No branch created by action. Skipping remaining steps."
            echo "SKIP_REMAINING=true" >> $GITHUB_ENV
          fi

      - name: Configure Git
        if: env.SKIP_REMAINING != 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Checkout and Fetch the Detected Branch
        if: env.SKIP_REMAINING != 'true'
        run: |
          git fetch origin ${{ env.CURRENT_BRANCH }}
          git checkout -B ${{ env.CURRENT_BRANCH }} origin/${{ env.CURRENT_BRANCH }}

      - name: Amend Commit with Signed-off-by
        if: env.SKIP_REMAINING != 'true'
        run: |
          if git diff --cached --quiet; then
            echo "No changes detected to amend."
          else
            git commit --amend --no-edit --signoff
          fi
          
      - name: Push Changes Back to Remote Branch
        if: env.SKIP_REMAINING != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --force-with-lease origin ${{ env.CURRENT_BRANCH }}
