name: Auto Label PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Auto-label PR
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  labels:
    backend:
      - backend/**
    frontend:
      - src/**
      - public/**
    ci:
      - .github/workflows/**
    config:
      - tailwind.config.js
      - vite.config.ts
      - eslint.config.js
      - tsconfig*.json
    documentation:
      - README.md
      - LICENSE
      - .github/ISSUE_TEMPLATE/**
    docker:
      - Dockerfile
      - docker-compose.yml
      - .dockerignore
    other:
      - "*"
